---
  - name: Install memcached from package
    apt: name=memcached state=latest

  - name: Enable memcached service
    service: name=memcached state=started enabled=true

  - name: Write memcached.conf
    action: template src=memcached.conf.j2 dest=/etc/memcached.conf mode=0644
    notify:
      - restart memcached